ghidra_arch_lookup = {'6502': {'6502:LE:16:default': {'desc': '6502 Microcontroller Family',
                                 'endian': 'little',
                                 'size': '16',
                                 'variant': 'default',
                                 'version': '1.0'},
          '65C02:LE:16:default': {'desc': '65C02 Microcontroller Family',
                                  'endian': 'little',
                                  'size': '16',
                                  'variant': 'default',
                                  'version': '1.0'}},
 '6800': {'6809:BE:16:default': {'desc': '6809 Microprocessor',
                                 'endian': 'big',
                                 'size': '16',
                                 'variant': 'default',
                                 'version': '1.0'},
          'H6309:BE:16:default': {'desc': 'Hitachi 6309 Microprocessor, '
                                          'extension of 6809, 6309 addressing '
                                          'modes, missing many instructions',
                                  'endian': 'big',
                                  'size': '16',
                                  'variant': 'default',
                                  'version': '1.0'}},
 '68000': {'68000:BE:32:Coldfire': {'desc': 'Motorola 32-bit Coldfire',
                                    'endian': 'big',
                                    'size': '32',
                                    'variant': 'Coldfire',
                                    'version': '1.1'},
           '68000:BE:32:MC68020': {'desc': 'Motorola 32-bit 68020',
                                   'endian': 'big',
                                   'size': '32',
                                   'variant': 'MC68020',
                                   'version': '1.1'},
           '68000:BE:32:MC68030': {'desc': 'Motorola 32-bit 68030',
                                   'endian': 'big',
                                   'size': '32',
                                   'variant': 'MC68030',
                                   'version': '1.1'},
           '68000:BE:32:default': {'desc': 'Motorola 32-bit 68040',
                                   'endian': 'big',
                                   'size': '32',
                                   'variant': 'default',
                                   'version': '1.1'}},
 '6805': {'6805:BE:16:default': {'desc': '6805 Microcontroller Family',
                                 'endian': 'big',
                                 'size': '16',
                                 'variant': 'default',
                                 'version': '1.0'}},
 '8048': {'8048:LE:16:default': {'desc': '8048 Microcontroller Family',
                                 'endian': 'little',
                                 'size': '16',
                                 'variant': 'default',
                                 'version': '1.0'}},
 '8051': {'80251:BE:24:default': {'desc': '80251 Microcontroller Family',
                                  'endian': 'big',
                                  'size': '16',
                                  'variant': 'default',
                                  'version': '2.0'},
          '80390:BE:24:default': {'desc': '80390 in flat mode',
                                  'endian': 'big',
                                  'size': '16',
                                  'variant': 'default',
                                  'version': '1.0'},
          '8051:BE:16:default': {'desc': '8051 Microcontroller Family',
                                 'endian': 'big',
                                 'size': '16',
                                 'variant': 'default',
                                 'version': '2.0'},
          '8051:BE:24:mx51': {'desc': 'NXP/Phillips MX51',
                              'endian': 'big',
                              'size': '16',
                              'variant': 'mx51',
                              'version': '2.0'}},
 '8085': {'8085:LE:16:default': {'desc': 'Intel 8085',
                                 'endian': 'little',
                                 'size': '16',
                                 'variant': 'default',
                                 'version': '1.0'}},
 'AARCH64': {'AARCH64:BE:32:ilp32': {'desc': 'Generic ARM64 v8.5-A LE '
                                             'instructions, BE data, ilp32',
                                     'endian': 'big',
                                     'size': '32',
                                     'variant': 'ilp32',
                                     'version': '1.5'},
             'AARCH64:BE:64:v8A': {'desc': 'Generic ARM64 v8.5-A LE '
                                           'instructions, BE data, missing '
                                           'some 8.5 vector',
                                   'endian': 'big',
                                   'size': '64',
                                   'variant': 'v8A',
                                   'version': '1.6'},
             'AARCH64:LE:32:ilp32': {'desc': 'Generic ARM64 v8.5-A LE '
                                             'instructions, LE data, ilp32',
                                     'endian': 'little',
                                     'size': '32',
                                     'variant': 'ilp32',
                                     'version': '1.5'},
             'AARCH64:LE:64:v8A': {'desc': 'Generic ARM64 v8.5-A LE '
                                           'instructions, LE data, missing '
                                           'some 8.5 vector',
                                   'endian': 'little',
                                   'size': '64',
                                   'variant': 'v8A',
                                   'version': '1.6'}},
 'ARM': {'ARM:BE:32:Cortex': {'desc': 'ARM Cortex / Thumb big endian',
                              'endian': 'big',
                              'size': '32',
                              'variant': 'Cortex',
                              'version': '1.107'},
         'ARM:BE:32:v4': {'desc': 'Generic ARM v4 big endian',
                          'endian': 'big',
                          'size': '32',
                          'variant': 'v4',
                          'version': '1.107'},
         'ARM:BE:32:v4t': {'desc': 'Generic ARM/Thumb v4 big endian '
                                   '(T-variant)',
                           'endian': 'big',
                           'size': '32',
                           'variant': 'v4t',
                           'version': '1.107'},
         'ARM:BE:32:v5': {'desc': 'Generic ARM v5 big endian',
                          'endian': 'big',
                          'size': '32',
                          'variant': 'v5',
                          'version': '1.101'},
         'ARM:BE:32:v5t': {'desc': 'Generic ARM/Thumb v5 big endian '
                                   '(T-variant)',
                           'endian': 'big',
                           'size': '32',
                           'variant': 'v5t',
                           'version': '1.107'},
         'ARM:BE:32:v6': {'desc': 'Generic ARM/Thumb v6 big endian',
                          'endian': 'big',
                          'size': '32',
                          'variant': 'v6',
                          'version': '1.107'},
         'ARM:BE:32:v7': {'desc': 'Generic ARM/Thumb v7 big endian',
                          'endian': 'big',
                          'size': '32',
                          'variant': 'v7',
                          'version': '1.107'},
         'ARM:BE:32:v8': {'desc': 'Generic ARM/Thumb v8 big endian',
                          'endian': 'big',
                          'size': '32',
                          'variant': 'v8',
                          'version': '1.107'},
         'ARM:BE:32:v8T': {'desc': 'Generic ARM/Thumb v8 big endian (Thumb is '
                                   'default)',
                           'endian': 'big',
                           'size': '32',
                           'variant': 'v8T',
                           'version': '1.107'},
         'ARM:LE:32:Cortex': {'desc': 'ARM Cortex / Thumb little endian',
                              'endian': 'little',
                              'size': '32',
                              'variant': 'Cortex',
                              'version': '1.107'},
         'ARM:LE:32:v4': {'desc': 'Generic ARM v4 little endian',
                          'endian': 'little',
                          'size': '32',
                          'variant': 'v4',
                          'version': '1.107'},
         'ARM:LE:32:v4t': {'desc': 'Generic ARM/Thumb v4 little endian '
                                   '(T-variant)',
                           'endian': 'little',
                           'size': '32',
                           'variant': 'v4t',
                           'version': '1.107'},
         'ARM:LE:32:v5': {'desc': 'Generic ARM v5 little endian',
                          'endian': 'little',
                          'size': '32',
                          'variant': 'v5',
                          'version': '1.107'},
         'ARM:LE:32:v5t': {'desc': 'Generic ARM/Thumb v5 little endian '
                                   '(T-variant)',
                           'endian': 'little',
                           'size': '32',
                           'variant': 'v5t',
                           'version': '1.107'},
         'ARM:LE:32:v6': {'desc': 'Generic ARM/Thumb v6 little endian',
                          'endian': 'little',
                          'size': '32',
                          'variant': 'v6',
                          'version': '1.107'},
         'ARM:LE:32:v7': {'desc': 'Generic ARM/Thumb v7 little endian',
                          'endian': 'little',
                          'size': '32',
                          'variant': 'v7',
                          'version': '1.107'},
         'ARM:LE:32:v8': {'desc': 'Generic ARM/Thumb v8 little endian',
                          'endian': 'little',
                          'size': '32',
                          'variant': 'v8',
                          'version': '1.107'},
         'ARM:LE:32:v8T': {'desc': 'Generic ARM/Thumb v8 little endian (Thumb '
                                   'is default)',
                           'endian': 'little',
                           'size': '32',
                           'variant': 'v8T',
                           'version': '1.107'},
         'ARM:LEBE:32:v7LEInstruction': {'desc': 'Generic ARM/Thumb v7 little '
                                                 'endian instructions and big '
                                                 'endian data',
                                         'endian': 'big',
                                         'size': '32',
                                         'variant': 'v7LEInstruction',
                                         'version': '1.107'},
         'ARM:LEBE:32:v8LEInstruction': {'desc': 'Generic ARM/Thumb v8 little '
                                                 'endian instructions and big '
                                                 'endian data',
                                         'endian': 'big',
                                         'size': '32',
                                         'variant': 'v8LEInstruction',
                                         'version': '1.107'}},
 'AppleSilicon': {'AARCH64:LE:64:AppleSilicon': {'desc': 'AppleSilicon ARM '
                                                         'v8.5-A LE '
                                                         'instructions, LE '
                                                         'data, AMX extensions',
                                                 'endian': 'little',
                                                 'size': '64',
                                                 'variant': 'AppleSilicon',
                                                 'version': '1.5'}},
 'BPF': {'BPF:LE:32:default': {'desc': 'BPF processor 32-bit little-endian',
                               'endian': 'little',
                               'size': '32',
                               'variant': 'default',
                               'version': '1.0'}},
 'CP1600': {'CP1600:BE:16:default': {'desc': 'General Instruments CP1600',
                                     'endian': 'big',
                                     'size': '16',
                                     'variant': 'default',
                                     'version': '1.0'}},
 'CR16': {'CR16C:LE:16:default': {'desc': "National Semiconductor's "
                                          'CompactRISC CR16C little endian',
                                  'endian': 'little',
                                  'size': '16',
                                  'variant': 'default',
                                  'version': '1.1'}},
 'Dalvik': {'Dalvik:LE:32:DEX_Android10': {'desc': 'Dalvik DEX Android10',
                                           'endian': 'little',
                                           'size': '32',
                                           'variant': 'DEX Android10',
                                           'version': '1.0'},
            'Dalvik:LE:32:DEX_Android11': {'desc': 'Dalvik DEX Android11',
                                           'endian': 'little',
                                           'size': '32',
                                           'variant': 'DEX Android11',
                                           'version': '1.0'},
            'Dalvik:LE:32:DEX_Android12': {'desc': 'Dalvik DEX Android12',
                                           'endian': 'little',
                                           'size': '32',
                                           'variant': 'DEX Android12',
                                           'version': '1.0'},
            'Dalvik:LE:32:DEX_Android13': {'desc': 'Dalvik DEX Android13',
                                           'endian': 'little',
                                           'size': '32',
                                           'variant': 'DEX Android13',
                                           'version': '1.0'},
            'Dalvik:LE:32:DEX_Base': {'desc': 'Dalvik Base',
                                      'endian': 'little',
                                      'size': '32',
                                      'variant': 'DEX-Base',
                                      'version': '1.0'},
            'Dalvik:LE:32:DEX_KitKat': {'desc': 'Dalvik DEX KitKat',
                                        'endian': 'little',
                                        'size': '32',
                                        'variant': 'DEX KitKat',
                                        'version': '1.0'},
            'Dalvik:LE:32:DEX_Lollipop': {'desc': 'Dalvik DEX Lollipop',
                                          'endian': 'little',
                                          'size': '32',
                                          'variant': 'DEX Lollipop',
                                          'version': '1.0'},
            'Dalvik:LE:32:DEX_Nougat': {'desc': 'Dalvik DEX Nougat',
                                        'endian': 'little',
                                        'size': '32',
                                        'variant': 'DEX Nougat',
                                        'version': '1.0'},
            'Dalvik:LE:32:DEX_Oreo': {'desc': 'Dalvik DEX Oreo',
                                      'endian': 'little',
                                      'size': '32',
                                      'variant': 'DEX Oreo',
                                      'version': '1.0'},
            'Dalvik:LE:32:DEX_Pie': {'desc': 'Dalvik DEX Pie',
                                     'endian': 'little',
                                     'size': '32',
                                     'variant': 'DEX Pie',
                                     'version': '1.0'},
            'Dalvik:LE:32:Marshmallow': {'desc': 'Dalvik DEX Marshmallow',
                                         'endian': 'little',
                                         'size': '32',
                                         'variant': 'DEX Marshmallow',
                                         'version': '1.0'},
            'Dalvik:LE:32:ODEX_KitKat': {'desc': 'Dalvik ODEX KitKat',
                                         'endian': 'little',
                                         'size': '32',
                                         'variant': 'ODEX KitKat',
                                         'version': '1.0'},
            'Dalvik:LE:32:default': {'desc': 'Dalvik Base',
                                     'endian': 'little',
                                     'size': '32',
                                     'variant': 'default',
                                     'version': '1.0'}},
 'HC05': {'HC05:BE:16:M68HC05TB': {'desc': 'HC05 (6805) Microcontroller Family '
                                           '- M68HC05TB',
                                   'endian': 'big',
                                   'size': '16',
                                   'variant': 'M68HC05TB',
                                   'version': '1.0'},
          'HC05:BE:16:default': {'desc': 'HC05 (6805) Microcontroller Family',
                                 'endian': 'big',
                                 'size': '16',
                                 'variant': 'default',
                                 'version': '1.0'}},
 'HC08': {'HC08:BE:16:MC68HC908QY4': {'desc': 'HC08 Microcontroller Family - '
                                              'MC68HC908QY4',
                                      'endian': 'big',
                                      'size': '16',
                                      'variant': 'MC68HC908QY4',
                                      'version': '1.0'},
          'HC08:BE:16:default': {'desc': 'HC08 Microcontroller Family',
                                 'endian': 'big',
                                 'size': '16',
                                 'variant': 'default',
                                 'version': '1.0'}},
 'HCS08': {'HCS08:BE:16:MC9S08GB60': {'desc': 'HCS08 Microcontroller Family - '
                                              'MC9S08GB60',
                                      'endian': 'big',
                                      'size': '16',
                                      'variant': 'MC9S08GB60',
                                      'version': '1.0'},
           'HCS08:BE:16:default': {'desc': 'HCS08 Microcontroller Family',
                                   'endian': 'big',
                                   'size': '16',
                                   'variant': 'default',
                                   'version': '1.0'}},
 'HCS12': {'HC-12:BE:16:default': {'desc': 'HC12 Microcontroller Family',
                                   'endian': 'big',
                                   'size': '16',
                                   'variant': 'default',
                                   'version': '2.0'},
           'HCS-12:BE:24:default': {'desc': 'HCS12 Microcontroller Family',
                                    'endian': 'big',
                                    'size': '24',
                                    'variant': 'default',
                                    'version': '2.0'},
           'HCS-12X:BE:24:default': {'desc': 'HCS12X Microcontroller Family',
                                     'endian': 'big',
                                     'size': '24',
                                     'variant': 'default',
                                     'version': '2.0'},
           'HCS12:BE:24:default': {'desc': 'HCS12X Microcontroller Family',
                                   'endian': 'big',
                                   'size': '24',
                                   'variant': 'default',
                                   'version': '2.0'}},
 'JVM': {'JVM:BE:32:default': {'desc': 'Generic JVM',
                               'endian': 'big',
                               'size': '32',
                               'variant': 'default',
                               'version': '1.1'}},
 'MCS96': {'MCS96:LE:16:default': {'desc': 'Intel MCS-96 Microcontroller '
                                           'Family',
                                   'endian': 'little',
                                   'size': '16',
                                   'variant': 'default',
                                   'version': '1.0'}},
 'PIC24': {'PIC-24E:LE:24:default': {'desc': 'PIC-24E',
                                     'endian': 'little',
                                     'size': '24',
                                     'variant': '24E',
                                     'version': '1.4'},
           'PIC-24F:LE:24:default': {'desc': 'PIC-24F',
                                     'endian': 'little',
                                     'size': '24',
                                     'variant': '24F',
                                     'version': '1.4'},
           'PIC-24H:LE:24:default': {'desc': 'PIC-24H',
                                     'endian': 'little',
                                     'size': '24',
                                     'variant': '24H',
                                     'version': '1.4'},
           'dsPIC30F:LE:24:default': {'desc': 'dsPIC30F',
                                      'endian': 'little',
                                      'size': '24',
                                      'variant': 'default',
                                      'version': '1.4'},
           'dsPIC33C:LE:24:default': {'desc': 'dsPIC33C',
                                      'endian': 'little',
                                      'size': '24',
                                      'variant': 'default',
                                      'version': '1.4'},
           'dsPIC33E:LE:24:default': {'desc': 'dsPIC33E',
                                      'endian': 'little',
                                      'size': '24',
                                      'variant': 'default',
                                      'version': '1.4'},
           'dsPIC33F:LE:24:default': {'desc': 'dsPIC33F',
                                      'endian': 'little',
                                      'size': '24',
                                      'variant': 'default',
                                      'version': '1.4'}},
 'SPARCV9': {'sparc:BE:32:default': {'desc': 'Sparc V9 32-bit',
                                     'endian': 'big',
                                     'size': '32',
                                     'variant': 'default',
                                     'version': '1.4'},
             'sparc:BE:64:default': {'desc': 'Sparc V9 64-bit',
                                     'endian': 'big',
                                     'size': '64',
                                     'variant': 'default',
                                     'version': '1.4'}},
 'SUPERH4': {'SuperH4:BE:32:default': {'desc': 'SuperH-4(a) (SH4) big endian',
                                       'endian': 'big',
                                       'size': '32',
                                       'variant': 'default',
                                       'version': '1.01'},
             'SuperH4:LE:32:default': {'desc': 'SuperH-4(a) (SH4) little '
                                               'endian',
                                       'endian': 'little',
                                       'size': '32',
                                       'variant': 'default',
                                       'version': '1.01'}},
 'TI_MSP430': {'TI_MSP430:LE:16:default': {'desc': 'TI MSP430 16-Bit '
                                                   'MicroController',
                                           'endian': 'little',
                                           'size': '16',
                                           'variant': 'default',
                                           'version': '1.4'},
               'TI_MSP430X:LE:32:default': {'desc': 'TI MSP430X 20-Bit '
                                                    'MicroController',
                                            'endian': 'little',
                                            'size': '32',
                                            'variant': 'default',
                                            'version': '1.4'}},
 'V850': {'V850:LE:32:default': {'desc': 'Renesas V850 family',
                                 'endian': 'little',
                                 'size': '32',
                                 'variant': 'E1, E2, E2M',
                                 'version': '1.0'}},
 'AVR32A': {'avr32:BE:32:default': {'desc': 'Generic AVR32-A big-endian',
                                    'endian': 'big',
                                    'size': '32',
                                    'variant': 'default',
                                    'version': '2.0'}},
 'AVR8': {'avr8:LE:16:atmega256': {'desc': 'AVR8 for an Atmega 256',
                                   'endian': 'little',
                                   'size': '24',
                                   'variant': 'atmega256',
                                   'version': '1.4'},
          'avr8:LE:16:default': {'desc': 'AVR8 with 16-bit word addressable '
                                         'code space',
                                 'endian': 'little',
                                 'size': '16',
                                 'variant': 'default',
                                 'version': '1.3'},
          'avr8:LE:16:extended': {'desc': 'AVR8 with 22-bit word addressable '
                                          'with EIND code space',
                                  'endian': 'little',
                                  'size': '24',
                                  'variant': 'extended',
                                  'version': '1.4'},
          'avr8:LE:24:xmega': {'desc': 'AVR8 for an Xmega',
                               'endian': 'little',
                               'size': '24',
                               'variant': 'Xmega',
                               'version': '1.4'}},
 'DATA': {'DATA:BE:64:default': {'desc': 'Raw Data File (Big Endian)',
                                 'endian': 'big',
                                 'size': '64',
                                 'variant': 'default',
                                 'version': '1.0'},
          'DATA:LE:64:default': {'desc': 'Raw Data File (Little Endian)',
                                 'endian': 'little',
                                 'size': '64',
                                 'variant': 'default',
                                 'version': '1.0'}},
 'EBPF': {'eBPF:LE:64:default': {'desc': 'eBPF processor 64-bit little-endian',
                                 'endian': 'little',
                                 'size': '64',
                                 'variant': 'default',
                                 'version': '1.0'}},
 'LOONGARCH': {'Loongarch:LE:32:ilp32d': {'desc': 'Loongson 3 32-bit with '
                                                  '64-bit FP',
                                          'endian': 'little',
                                          'size': '32',
                                          'variant': 'ilp32d',
                                          'version': '1.0'},
               'Loongarch:LE:32:ilp32f': {'desc': 'Loongson 3 32-bit with '
                                                  '32-bit FP',
                                          'endian': 'little',
                                          'size': '32',
                                          'variant': 'ilp32f',
                                          'version': '1.0'},
               'Loongarch:LE:64:lp64d': {'desc': 'Loongson 3 64-bit with '
                                                 '64-bit FP',
                                         'endian': 'little',
                                         'size': '64',
                                         'variant': 'lp64d',
                                         'version': '1.0'},
               'Loongarch:LE:64:lp64f': {'desc': 'Loongson 3 64-bit with '
                                                 '32-bit FP',
                                         'endian': 'little',
                                         'size': '64',
                                         'variant': 'lp64f',
                                         'version': '1.0'}},
 'M8C': {'M8C:BE:16:default': {'desc': 'Cypress M8C Microcontroller Family',
                               'endian': 'big',
                               'size': '16',
                               'variant': 'default',
                               'version': '1.0'}},
 'MIPS': {'MIPS:BE:32:R6': {'desc': 'MIPS32 Release-6 32-bit addresses, big '
                                    'endian, with microMIPS',
                            'endian': 'big',
                            'size': '32',
                            'variant': 'R6',
                            'version': '1.8'},
          'MIPS:BE:32:default': {'desc': 'MIPS32 32-bit addresses, big endian, '
                                         'with mips16e',
                                 'endian': 'big',
                                 'size': '32',
                                 'variant': 'default',
                                 'version': '1.8'},
          'MIPS:BE:32:micro': {'desc': 'MIPS32 32-bit addresses, big endian, '
                                       'with microMIPS',
                               'endian': 'big',
                               'size': '32',
                               'variant': 'micro',
                               'version': '1.8'},
          'MIPS:BE:64:64-32R6addr': {'desc': 'MIPS64 Release-6 big endian with '
                                             '32 bit addressing and microMIPS',
                                     'endian': 'big',
                                     'size': '32',
                                     'variant': '64-32addr-R6',
                                     'version': '1.8'},
          'MIPS:BE:64:64-32addr': {'desc': 'MIPS64 32-bit addresses, big '
                                           'endian, with mips16e',
                                   'endian': 'big',
                                   'size': '32',
                                   'variant': '64-32addr',
                                   'version': '1.8'},
          'MIPS:BE:64:R6': {'desc': 'MIPS64 Release-6 64-bit addresses, big '
                                    'endian, with microMIPS',
                            'endian': 'big',
                            'size': '64',
                            'variant': 'R6',
                            'version': '1.8'},
          'MIPS:BE:64:default': {'desc': 'MIPS64 64-bit addresses, big endian, '
                                         'with mips16e',
                                 'endian': 'big',
                                 'size': '64',
                                 'variant': 'default',
                                 'version': '1.8'},
          'MIPS:BE:64:micro': {'desc': 'MIPS64 64-bit addresses, big endian, '
                                       'with microMIPS',
                               'endian': 'big',
                               'size': '64',
                               'variant': 'micro',
                               'version': '1.8'},
          'MIPS:BE:64:micro64-32addr': {'desc': 'MIPS64 32-bit addresses, big '
                                                'endian, with microMIPS',
                                        'endian': 'big',
                                        'size': '32',
                                        'variant': '64-32addr-micro',
                                        'version': '1.8'},
          'MIPS:LE:32:R6': {'desc': 'MIPS32 Release-6 32-bit addresses, little '
                                    'endian, with microMIPS',
                            'endian': 'little',
                            'size': '32',
                            'variant': 'R6',
                            'version': '1.8'},
          'MIPS:LE:32:default': {'desc': 'MIPS32 32-bit addresses, little '
                                         'endian, with mips16e',
                                 'endian': 'little',
                                 'size': '32',
                                 'variant': 'default',
                                 'version': '1.8'},
          'MIPS:LE:32:micro': {'desc': 'MIPS32 32-bit addresses, little '
                                       'endian, with microMIPS',
                               'endian': 'little',
                               'size': '32',
                               'variant': 'micro',
                               'version': '1.8'},
          'MIPS:LE:64:64-32R6addr': {'desc': 'MIPS64 Release-6 with 32-bit '
                                             'addresses, little endian, with '
                                             'microMIPS',
                                     'endian': 'little',
                                     'size': '32',
                                     'variant': '64-32addr-R6',
                                     'version': '1.8'},
          'MIPS:LE:64:64-32addr': {'desc': 'MIPS64 32-bit addresses, little '
                                           'endian, with mips16e',
                                   'endian': 'little',
                                   'size': '32',
                                   'variant': '64-32addr',
                                   'version': '1.8'},
          'MIPS:LE:64:R6': {'desc': 'MIPS64 Release-6 64-bit addresses, little '
                                    'endian, with microMIPS',
                            'endian': 'little',
                            'size': '64',
                            'variant': 'R6',
                            'version': '1.8'},
          'MIPS:LE:64:default': {'desc': 'MIPS64 64-bit addreses, little '
                                         'endian, with mips16e',
                                 'endian': 'little',
                                 'size': '64',
                                 'variant': 'default',
                                 'version': '1.8'},
          'MIPS:LE:64:micro': {'desc': 'MIPS64 64-bit addresses, little '
                                       'endian, with microMIPS',
                               'endian': 'little',
                               'size': '64',
                               'variant': 'micro',
                               'version': '1.8'},
          'MIPS:LE:64:micro64-32addr': {'desc': 'MIPS64 32-bit addresses, '
                                                'little endian, with microMIPS',
                                        'endian': 'little',
                                        'size': '32',
                                        'variant': '64-32addr-micro',
                                        'version': '1.8'}},
'MIPSeb': {'MIPS:BE:32:R6': {'desc': 'MIPS32 Release-6 32-bit addresses, big '
                                    'endian, with microMIPS',
                            'endian': 'big',
                            'size': '32',
                            'variant': 'R6',
                            'version': '1.8'},
          'MIPS:BE:32:default': {'desc': 'MIPS32 32-bit addresses, big endian, '
                                         'with mips16e',
                                 'endian': 'big',
                                 'size': '32',
                                 'variant': 'default',
                                 'version': '1.8'},
          'MIPS:BE:32:micro': {'desc': 'MIPS32 32-bit addresses, big endian, '
                                       'with microMIPS',
                               'endian': 'big',
                               'size': '32',
                               'variant': 'micro',
                               'version': '1.8'},
          'MIPS:BE:64:64-32R6addr': {'desc': 'MIPS64 Release-6 big endian with '
                                             '32 bit addressing and microMIPS',
                                     'endian': 'big',
                                     'size': '32',
                                     'variant': '64-32addr-R6',
                                     'version': '1.8'},
          'MIPS:BE:64:64-32addr': {'desc': 'MIPS64 32-bit addresses, big '
                                           'endian, with mips16e',
                                   'endian': 'big',
                                   'size': '32',
                                   'variant': '64-32addr',
                                   'version': '1.8'},
          'MIPS:BE:64:R6': {'desc': 'MIPS64 Release-6 64-bit addresses, big '
                                    'endian, with microMIPS',
                            'endian': 'big',
                            'size': '64',
                            'variant': 'R6',
                            'version': '1.8'},
          'MIPS:BE:64:default': {'desc': 'MIPS64 64-bit addresses, big endian, '
                                         'with mips16e',
                                 'endian': 'big',
                                 'size': '64',
                                 'variant': 'default',
                                 'version': '1.8'},
          'MIPS:BE:64:micro': {'desc': 'MIPS64 64-bit addresses, big endian, '
                                       'with microMIPS',
                               'endian': 'big',
                               'size': '64',
                               'variant': 'micro',
                               'version': '1.8'},
          'MIPS:BE:64:micro64-32addr': {'desc': 'MIPS64 32-bit addresses, big '
                                                'endian, with microMIPS',
                                        'endian': 'big',
                                        'size': '32',
                                        'variant': '64-32addr-micro',
                                        'version': '1.8'}},
 'PA-RISC': {'pa-risc:BE:32:default': {'desc': 'Generic PA-RISC 32-bit big '
                                               'endian',
                                       'endian': 'big',
                                       'size': '32',
                                       'variant': 'default',
                                       'version': '1.3'}},
 'PIC12C5XX': {'PIC-12:LE:16:PIC-12C5xx': {'desc': 'PIC-12C5xx',
                                           'endian': 'little',
                                           'size': '16',
                                           'variant': 'PIC-12C5xx',
                                           'version': '1.0'}},
 'PIC16': {'PIC-16:LE:16:PIC-16': {'desc': 'PIC-16(C,CR)XXX',
                                   'endian': 'little',
                                   'size': '16',
                                   'variant': 'PIC-16',
                                   'version': '1.2'},
           'PIC-16:LE:16:PIC-16F': {'desc': 'PIC-16F(L)XXX',
                                    'endian': 'little',
                                    'size': '16',
                                    'variant': 'PIC-16F',
                                    'version': '1.2'}},
 'PIC16C5X': {'PIC-16:LE:16:PIC-16C5x': {'desc': 'PIC-16C5x',
                                         'endian': 'little',
                                         'size': '16',
                                         'variant': 'PIC-16C5x',
                                         'version': '1.1'}},
 'PIC17C7XX': {'PIC-17:LE:16:PIC-17C7xx': {'desc': 'PIC-17C7xx',
                                           'endian': 'little',
                                           'size': '16',
                                           'variant': 'PIC-17C7xx',
                                           'version': '1.0'}},
 'PIC18': {'PIC-18:LE:24:PIC-18': {'desc': 'PIC-18',
                                   'endian': 'little',
                                   'size': '24',
                                   'variant': 'PIC-18',
                                   'version': '1.0'}},
 'PPC': {'PowerPC:BE:32:4xx': {'desc': 'PowerPC 4xx 32-bit big endian embedded '
                                       'core',
                               'endian': 'big',
                               'size': '32',
                               'variant': '4xx',
                               'version': '1.5'},
         'PowerPC:BE:32:MPC8270': {'desc': 'Freescale MPC8280 32-bit big '
                                           'endian family (PowerQUICC-III)',
                                   'endian': 'big',
                                   'size': '32',
                                   'variant': 'MPC8270',
                                   'version': '1.5'},
         'PowerPC:BE:32:QUICC': {'desc': 'PowerQUICC-III 32-bit big endian '
                                         'family',
                                 'endian': 'big',
                                 'size': '32',
                                 'variant': 'PowerQUICC-III',
                                 'version': '1.5'},
         'PowerPC:BE:32:default': {'desc': 'PowerPC 32-bit big endian '
                                           'w/Altivec, G2',
                                   'endian': 'big',
                                   'size': '32',
                                   'variant': 'default',
                                   'version': '1.5'},
         'PowerPC:BE:32:e500': {'desc': 'PowerQUICC-III e500 32-bit big-endian '
                                        'family',
                                'endian': 'big',
                                'size': '32',
                                'variant': 'PowerQUICC-III-e500',
                                'version': '1.5'},
         'PowerPC:BE:32:e500mc': {'desc': 'PowerQUICC-III e500mc 32-bit '
                                          'big-endian family',
                                  'endian': 'big',
                                  'size': '32',
                                  'variant': 'PowerQUICC-III-e500mc',
                                  'version': '1.5'},
         'PowerPC:BE:64:64-32addr': {'desc': 'PowerPC 64-bit big endian '
                                             'w/Altivec and 32 bit addressing, '
                                             'G2',
                                     'endian': 'big',
                                     'size': '32',
                                     'variant': '64-32addr',
                                     'version': '1.5'},
         'PowerPC:BE:64:A2-32addr': {'desc': 'Power ISA 3.0 Big Endian w/EVX '
                                             'and 32-bit Addressing',
                                     'endian': 'big',
                                     'size': '32',
                                     'variant': 'PowerISA-64-32addr',
                                     'version': '1.5'},
         'PowerPC:BE:64:A2ALT': {'desc': 'Power ISA 3.0 Big Endian w/Altivec',
                                 'endian': 'big',
                                 'size': '64',
                                 'variant': 'PowerISA-Altivec',
                                 'version': '1.5'},
         'PowerPC:BE:64:A2ALT-32addr': {'desc': 'Power ISA 3.0 Big Endian '
                                                'w/Altivec and 32-bit '
                                                'Addressing',
                                        'endian': 'big',
                                        'size': '32',
                                        'variant': 'PowerISA-Altivec-64-32addr',
                                        'version': '1.5'},
         'PowerPC:BE:64:VLE-32addr': {'desc': 'Power ISA 3.0 Big Endian w/VLE, '
                                              'EVX and 32-bit Addressing ',
                                      'endian': 'big',
                                      'size': '32',
                                      'variant': 'PowerISA-VLE-64-32addr',
                                      'version': '1.5'},
         'PowerPC:BE:64:VLEALT-32addr': {'desc': 'Power ISA 3.0 Big Endian '
                                                 'w/VLE, Altivec and 32-bit '
                                                 'Addressing',
                                         'endian': 'big',
                                         'size': '32',
                                         'variant': 'PowerISA-VLE-Altivec-64-32addr',
                                         'version': '1.5'},
         'PowerPC:BE:64:default': {'desc': 'PowerPC 64-bit big endian '
                                           'w/Altivec, G2',
                                   'endian': 'big',
                                   'size': '64',
                                   'variant': 'default',
                                   'version': '1.5'},
         'PowerPC:LE:32:4xx': {'desc': 'PowerPC 4xx 32-bit little endian '
                                       'embedded core',
                               'endian': 'little',
                               'size': '32',
                               'variant': '4xx',
                               'version': '1.5'},
         'PowerPC:LE:32:QUICC': {'desc': 'PowerQUICC-III 32-bit little endian '
                                         'family',
                                 'endian': 'little',
                                 'size': '32',
                                 'variant': 'PowerQUICC-III',
                                 'version': '1.5'},
         'PowerPC:LE:32:default': {'desc': 'PowerPC 32-bit little endian '
                                           'w/Altivec, G2',
                                   'endian': 'little',
                                   'size': '32',
                                   'variant': 'default',
                                   'version': '1.5'},
         'PowerPC:LE:32:e500': {'desc': 'PowerQUICC-III e500 32-bit '
                                        'little-endian family',
                                'endian': 'little',
                                'size': '32',
                                'variant': 'PowerQUICC-III-e500',
                                'version': '1.5'},
         'PowerPC:LE:32:e500mc': {'desc': 'PowerQUICC-III e500mc 32-bit '
                                          'little-endian family',
                                  'endian': 'little',
                                  'size': '32',
                                  'variant': 'PowerQUICC-III-e500mc',
                                  'version': '1.5'},
         'PowerPC:LE:64:64-32addr': {'desc': 'PowerPC 64-bit little endian '
                                             'w/Altivec and 32 bit addressing, '
                                             'G2',
                                     'endian': 'little',
                                     'size': '32',
                                     'variant': '64-32addr',
                                     'version': '1.5'},
         'PowerPC:LE:64:A2-32addr': {'desc': 'Power ISA 3.0 Little Endian '
                                             'w/EVX and 32-bit Addressing',
                                     'endian': 'little',
                                     'size': '32',
                                     'variant': 'PowerISA-64-32addr',
                                     'version': '1.5'},
         'PowerPC:LE:64:A2ALT': {'desc': 'Power ISA 3.0 Little Endian '
                                         'w/Altivec',
                                 'endian': 'little',
                                 'size': '64',
                                 'variant': 'PowerISA-Altivec',
                                 'version': '1.5'},
         'PowerPC:LE:64:A2ALT-32addr': {'desc': 'Power ISA 3.0 Little Endian '
                                                'w/Altivec and 32-bit '
                                                'Addressing',
                                        'endian': 'little',
                                        'size': '32',
                                        'variant': 'PowerISA-Altivec-64-32addr',
                                        'version': '1.5'},
         'PowerPC:LE:64:default': {'desc': 'PowerPC 64-bit little endian '
                                           'w/Altivec, G2',
                                   'endian': 'little',
                                   'size': '64',
                                   'variant': 'default',
                                   'version': '1.5'}},
 'RISCV': {'RISCV:LE:32:RV32G': {'desc': 'RISC-V 32 little general purpose',
                                 'endian': 'little',
                                 'size': '32',
                                 'variant': 'RV32G',
                                 'version': '1.3'},
           'RISCV:LE:32:RV32GC': {'desc': 'RISC-V 32 little general purpose '
                                          'compressed',
                                  'endian': 'little',
                                  'size': '32',
                                  'variant': 'RV32GC',
                                  'version': '1.3'},
           'RISCV:LE:32:RV32I': {'desc': 'RISC-V 32 little base',
                                 'endian': 'little',
                                 'size': '32',
                                 'variant': 'RV32I',
                                 'version': '1.3'},
           'RISCV:LE:32:RV32IC': {'desc': 'RISC-V 32 little base compressed',
                                  'endian': 'little',
                                  'size': '32',
                                  'variant': 'RV32IC',
                                  'version': '1.3'},
           'RISCV:LE:32:RV32IMC': {'desc': 'RISC-V 32 little base compressed',
                                   'endian': 'little',
                                   'size': '32',
                                   'variant': 'RV32IMC',
                                   'version': '1.3'},
           'RISCV:LE:32:default': {'desc': 'RISC-V 32 little default',
                                   'endian': 'little',
                                   'size': '32',
                                   'variant': 'default',
                                   'version': '1.3'},
           'RISCV:LE:64:RV64G': {'desc': 'RISC-V 64 little general purpose',
                                 'endian': 'little',
                                 'size': '64',
                                 'variant': 'RV64G',
                                 'version': '1.3'},
           'RISCV:LE:64:RV64GC': {'desc': 'RISC-V 64 little general purpose '
                                          'compressed',
                                  'endian': 'little',
                                  'size': '64',
                                  'variant': 'RV64GC',
                                  'version': '1.3'},
           'RISCV:LE:64:RV64I': {'desc': 'RISC-V 64 little base',
                                 'endian': 'little',
                                 'size': '64',
                                 'variant': 'RV64I',
                                 'version': '1.3'},
           'RISCV:LE:64:RV64IC': {'desc': 'RISC-V 64 little base compressed',
                                  'endian': 'little',
                                  'size': '64',
                                  'variant': 'RV64IC',
                                  'version': '1.3'},
           'RISCV:LE:64:default': {'desc': 'RISC-V 32 little default',
                                   'endian': 'little',
                                   'size': '64',
                                   'variant': 'default',
                                   'version': '1.3'}},
 'SUPERH': {'SuperH:BE:32:SH-1': {'desc': 'SuperH SH-1 processor 32-bit '
                                          'big-endian',
                                  'endian': 'big',
                                  'size': '32',
                                  'variant': 'SH-1',
                                  'version': '1.0'},
            'SuperH:BE:32:SH-2': {'desc': 'SuperH SH-2 processor 32-bit '
                                          'big-endian',
                                  'endian': 'big',
                                  'size': '32',
                                  'variant': 'SH-2',
                                  'version': '1.0'},
            'SuperH:BE:32:SH-2A': {'desc': 'SuperH SH-2A processor 32-bit '
                                           'big-endian',
                                   'endian': 'big',
                                   'size': '32',
                                   'variant': 'SH-2A',
                                   'version': '1.0'}},
 'TRICORE': {'tricore:LE:32:default': {'desc': 'Siemens Tricore Embedded '
                                               'Processor',
                                       'endian': 'little',
                                       'size': '32',
                                       'variant': 'default',
                                       'version': '1.7'},
             'tricore:LE:32:tc172x': {'desc': 'Siemens Tricore Embedded '
                                              'Processor TC1724/TC1728',
                                      'endian': 'little',
                                      'size': '32',
                                      'variant': 'TC172x',
                                      'version': '1.7'},
             'tricore:LE:32:tc176x': {'desc': 'Siemens Tricore Embedded '
                                              'Processor TC1762/TC1766',
                                      'endian': 'little',
                                      'size': '32',
                                      'variant': 'TC176x',
                                      'version': '1.7'},
             'tricore:LE:32:tc29x': {'desc': 'Siemens Tricore Embedded '
                                             'Processor TC29x',
                                     'endian': 'little',
                                     'size': '32',
                                     'variant': 'TC29x',
                                     'version': '1.7'}},
 'X86': {'x86:LE:16:Protected Mode': {'desc': 'Intel/AMD 16-bit x86 Protected '
                                              'Mode',
                                      'endian': 'little',
                                      'size': '16',
                                      'variant': 'Protected Mode',
                                      'version': '3.0'},
         'x86:LE:16:Real Mode': {'desc': 'Intel/AMD 16-bit x86 Real Mode',
                                 'endian': 'little',
                                 'size': '16',
                                 'variant': 'Real Mode',
                                 'version': '3.0'},
         'x86:LE:32:System Management Mode': {'desc': 'Intel/AMD 32-bit x86 '
                                                      'System Management Mode',
                                              'endian': 'little',
                                              'size': '32',
                                              'variant': 'System Management '
                                                         'Mode',
                                              'version': '3.0'},
         'x86:LE:32:default': {'desc': 'Intel/AMD 32-bit x86',
                               'endian': 'little',
                               'size': '32',
                               'variant': 'default',
                               'version': '3.0'},
         'x86:LE:64:compat32': {'desc': 'Intel/AMD 64-bit x86 in 32-bit '
                                        'compatibility mode (long mode off)',
                                'endian': 'little',
                                'size': '64',
                                'variant': 'compat32',
                                'version': '3.0'},
         'x86:LE:64:default': {'desc': 'Intel/AMD 64-bit x86',
                               'endian': 'little',
                               'size': '64',
                               'variant': 'default',
                               'version': '3.0'}},
 'X86-64': {'x86:LE:64:compat32': {'desc': 'Intel/AMD 64-bit x86 in 32-bit '
                                        'compatibility mode (long mode off)',
                                'endian': 'little',
                                'size': '64',
                                'variant': 'compat32',
                                'version': '3.0'},
         'x86:LE:64:default': {'desc': 'Intel/AMD 64-bit x86',
                               'endian': 'little',
                               'size': '64',
                               'variant': 'default',
                               'version': '3.0'}},
 'XTENSA': {'Xtensa:BE:32:default': {'desc': 'Tensilica Xtensa 32-bit '
                                             'big-endian',
                                     'endian': 'big',
                                     'size': '32',
                                     'variant': 'default',
                                     'version': '4.0'},
            'Xtensa:LE:32:default': {'desc': 'Tensilica Xtensa 32-bit '
                                             'little-endian',
                                     'endian': 'little',
                                     'size': '32',
                                     'variant': 'default',
                                     'version': '4.0'}},
 'Z80': {'z180:LE:16:default': {'desc': 'Zilog Z180',
                                'endian': 'little',
                                'size': '16',
                                'variant': 'default',
                                'version': '1.0'},
         'z182:LE:16:default': {'desc': 'Zilog Z182',
                                'endian': 'little',
                                'size': '16',
                                'variant': 'Z182',
                                'version': '1.0'},
         'z80:LE:16:default': {'desc': 'Zilog Z80',
                               'endian': 'little',
                               'size': '16',
                               'variant': 'default',
                               'version': '1.0'},
         'z8401x:LE:16:default': {'desc': 'Zilog Z8401x (IPC) microcontroller',
                                  'endian': 'little',
                                  'size': '16',
                                  'variant': 'Z8401x',
                                  'version': '1.0'}}}